spring.application.name=demo


#spring.ai.google.genai.api-key=${GOOGLE_API_KEY}
#spring.ai.google.genai.chat.model=gemini-3.7-flash

#spring.ai.anthropic.api-key=${ANTHROPIC_API_KEY}
#spring.ai.anthropic.chat.model=claude-sonnet-5

# H2 Database Configuration
#spring.datasource.url=jdbc:h2:file:./data/db/chatmemory;AUTO_SERVER=TRUE
#spring.datasource.driver-class-name=org.h2.Driver
#spring.ai.chat.memory.repository.jdbc.initialize-schema=always
#spring.h2.console.enabled=true
#spring.datasource.username=sa
#spring.datasource.password=

spring.datasource.url=jdbc:postgresql://localhost:5433/springai
spring.datasource.username=postgres
spring.datasource.password=admin@123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.ai.chat.memory.repository.jdbc.initialize-schema=always

spring.ai.openai.api-key=${GROK_API_KEY}
spring.ai.openai.base-url=https://api.groq.com/openai/v1
#spring.ai.openai.chat.model=openai/gpt-oss-120b
spring.ai.openai.chat.model=qwen/qwen3.8-27b

spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.embedding.model=nomic-embed-text
spring.ai.model.embedding=ollama
spring.ai.model.chat=openai
spring.ai.vectorstore.pgvector.initialize-schema=true


logging.level.org.springframework.ai.chat.client.advisor=DEBUG