spring.application.name=demo


#spring.ai.google.genai.api-key=${GOOGLE_API_KEY}
#spring.ai.google.genai.chat.model=gemini-3.7-flash

#spring.ai.anthropic.api-key=${ANTHROPIC_API_KEY}
#spring.ai.anthropic.chat.model=claude-sonnet-5


spring.ai.openai.api-key=${GROK_API_KEY}
spring.ai.openai.base-url=https://api.groq.com/openai/v1
spring.ai.openai.chat.model=openai/gpt-oss-120b

logging.level.org.springframework.ai.chat.client.advisor=DEBUG