package com.course.demo.advisors;

import org.springframework.ai.chat.client.ChatClientRequest;
import org.springframework.ai.chat.client.ChatClientResponse;
import org.springframework.ai.chat.client.advisor.api.AdvisorChain;
import org.springframework.ai.chat.client.advisor.api.BaseAdvisor;
import org.springframework.ai.chat.messages.AssistantMessage;
import org.springframework.ai.chat.model.ChatResponse;
import org.springframework.ai.chat.model.Generation;

import java.util.List;

public class DisclaimerAdvisor implements BaseAdvisor {

    private final int order;
    private static String DISCLAIMER = """
            ---
            _This response was generated by AI & may contain inaccuracies._ 
            """;


    public DisclaimerAdvisor(int order) {
        this.order = order;
    }

    @Override
    public ChatClientRequest before(ChatClientRequest chatClientRequest, AdvisorChain advisorChain) {
        return chatClientRequest;
    }

    @Override
    public ChatClientResponse after(ChatClientResponse chatClientResponse, AdvisorChain advisorChain) {
        ChatResponse chatResponse = chatClientResponse.chatResponse();

        if (chatClientResponse == null || chatResponse.getResult() == null) {
            return chatClientResponse;
        }

        AssistantMessage original = chatResponse.getResult().getOutput();
        AssistantMessage withDisclaimer = AssistantMessage.builder()
                .content(original.getText() + DISCLAIMER)
                .properties(original.getMetadata())
                .toolCalls(original.getToolCalls())
                .media(original.getMedia())
                .build();

        Generation updateGeneration = new Generation(withDisclaimer,
                chatResponse.getResult().getMetadata());
        ChatResponse updatedChatResponse = ChatResponse.builder()
                .from(chatResponse)
                .generations(List.of(updateGeneration))
                .build();

        return chatClientResponse.mutate()
                .chatResponse(updatedChatResponse)
                .build();
    }

    @Override
    public int getOrder() {
        return order;
    }
}
